// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commitment.proto

#ifndef PROTOBUF_INCLUDED_commitment_2eproto
#define PROTOBUF_INCLUDED_commitment_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "crypto-curve/curve_point.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_commitment_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_commitment_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_commitment_2eproto();
namespace safeheron {
namespace proto {
class KGD;
class KGDDefaultTypeInternal;
extern KGDDefaultTypeInternal _KGD_default_instance_;
class KGD_Num;
class KGD_NumDefaultTypeInternal;
extern KGD_NumDefaultTypeInternal _KGD_Num_default_instance_;
}  // namespace proto
}  // namespace safeheron
namespace google {
namespace protobuf {
template<> ::safeheron::proto::KGD* Arena::CreateMaybeMessage<::safeheron::proto::KGD>(Arena*);
template<> ::safeheron::proto::KGD_Num* Arena::CreateMaybeMessage<::safeheron::proto::KGD_Num>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace safeheron {
namespace proto {

// ===================================================================

class KGD :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.KGD) */ {
 public:
  KGD();
  virtual ~KGD();

  KGD(const KGD& from);

  inline KGD& operator=(const KGD& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KGD(KGD&& from) noexcept
    : KGD() {
    *this = ::std::move(from);
  }

  inline KGD& operator=(KGD&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const KGD& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KGD* internal_default_instance() {
    return reinterpret_cast<const KGD*>(
               &_KGD_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(KGD* other);
  friend void swap(KGD& a, KGD& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KGD* New() const final {
    return CreateMaybeMessage<KGD>(nullptr);
  }

  KGD* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<KGD>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const KGD& from);
  void MergeFrom(const KGD& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KGD* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string blindFactor = 2;
  void clear_blindfactor();
  static const int kBlindFactorFieldNumber = 2;
  const ::std::string& blindfactor() const;
  void set_blindfactor(const ::std::string& value);
  #if LANG_CXX11
  void set_blindfactor(::std::string&& value);
  #endif
  void set_blindfactor(const char* value);
  void set_blindfactor(const char* value, size_t size);
  ::std::string* mutable_blindfactor();
  ::std::string* release_blindfactor();
  void set_allocated_blindfactor(::std::string* blindfactor);

  // .safeheron.proto.CurvePoint y = 1;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 1;
  const ::safeheron::proto::CurvePoint& y() const;
  ::safeheron::proto::CurvePoint* release_y();
  ::safeheron::proto::CurvePoint* mutable_y();
  void set_allocated_y(::safeheron::proto::CurvePoint* y);

  // @@protoc_insertion_point(class_scope:safeheron.proto.KGD)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr blindfactor_;
  ::safeheron::proto::CurvePoint* y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_commitment_2eproto;
};
// -------------------------------------------------------------------

class KGD_Num :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.KGD_Num) */ {
 public:
  KGD_Num();
  virtual ~KGD_Num();

  KGD_Num(const KGD_Num& from);

  inline KGD_Num& operator=(const KGD_Num& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KGD_Num(KGD_Num&& from) noexcept
    : KGD_Num() {
    *this = ::std::move(from);
  }

  inline KGD_Num& operator=(KGD_Num&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const KGD_Num& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KGD_Num* internal_default_instance() {
    return reinterpret_cast<const KGD_Num*>(
               &_KGD_Num_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(KGD_Num* other);
  friend void swap(KGD_Num& a, KGD_Num& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KGD_Num* New() const final {
    return CreateMaybeMessage<KGD_Num>(nullptr);
  }

  KGD_Num* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<KGD_Num>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const KGD_Num& from);
  void MergeFrom(const KGD_Num& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KGD_Num* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string num = 1;
  void clear_num();
  static const int kNumFieldNumber = 1;
  const ::std::string& num() const;
  void set_num(const ::std::string& value);
  #if LANG_CXX11
  void set_num(::std::string&& value);
  #endif
  void set_num(const char* value);
  void set_num(const char* value, size_t size);
  ::std::string* mutable_num();
  ::std::string* release_num();
  void set_allocated_num(::std::string* num);

  // string blindFactor = 2;
  void clear_blindfactor();
  static const int kBlindFactorFieldNumber = 2;
  const ::std::string& blindfactor() const;
  void set_blindfactor(const ::std::string& value);
  #if LANG_CXX11
  void set_blindfactor(::std::string&& value);
  #endif
  void set_blindfactor(const char* value);
  void set_blindfactor(const char* value, size_t size);
  ::std::string* mutable_blindfactor();
  ::std::string* release_blindfactor();
  void set_allocated_blindfactor(::std::string* blindfactor);

  // @@protoc_insertion_point(class_scope:safeheron.proto.KGD_Num)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr num_;
  ::google::protobuf::internal::ArenaStringPtr blindfactor_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_commitment_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// KGD

// .safeheron.proto.CurvePoint y = 1;
inline bool KGD::has_y() const {
  return this != internal_default_instance() && y_ != nullptr;
}
inline const ::safeheron::proto::CurvePoint& KGD::y() const {
  const ::safeheron::proto::CurvePoint* p = y_;
  // @@protoc_insertion_point(field_get:safeheron.proto.KGD.y)
  return p != nullptr ? *p : *reinterpret_cast<const ::safeheron::proto::CurvePoint*>(
      &::safeheron::proto::_CurvePoint_default_instance_);
}
inline ::safeheron::proto::CurvePoint* KGD::release_y() {
  // @@protoc_insertion_point(field_release:safeheron.proto.KGD.y)
  
  ::safeheron::proto::CurvePoint* temp = y_;
  y_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* KGD::mutable_y() {
  
  if (y_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArenaNoVirtual());
    y_ = p;
  }
  // @@protoc_insertion_point(field_mutable:safeheron.proto.KGD.y)
  return y_;
}
inline void KGD::set_allocated_y(::safeheron::proto::CurvePoint* y) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(y_);
  }
  if (y) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      y = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, y, submessage_arena);
    }
    
  } else {
    
  }
  y_ = y;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.KGD.y)
}

// string blindFactor = 2;
inline void KGD::clear_blindfactor() {
  blindfactor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KGD::blindfactor() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.KGD.blindFactor)
  return blindfactor_.GetNoArena();
}
inline void KGD::set_blindfactor(const ::std::string& value) {
  
  blindfactor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.KGD.blindFactor)
}
#if LANG_CXX11
inline void KGD::set_blindfactor(::std::string&& value) {
  
  blindfactor_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.KGD.blindFactor)
}
#endif
inline void KGD::set_blindfactor(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  blindfactor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.KGD.blindFactor)
}
inline void KGD::set_blindfactor(const char* value, size_t size) {
  
  blindfactor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.KGD.blindFactor)
}
inline ::std::string* KGD::mutable_blindfactor() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.KGD.blindFactor)
  return blindfactor_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KGD::release_blindfactor() {
  // @@protoc_insertion_point(field_release:safeheron.proto.KGD.blindFactor)
  
  return blindfactor_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KGD::set_allocated_blindfactor(::std::string* blindfactor) {
  if (blindfactor != nullptr) {
    
  } else {
    
  }
  blindfactor_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), blindfactor);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.KGD.blindFactor)
}

// -------------------------------------------------------------------

// KGD_Num

// string num = 1;
inline void KGD_Num::clear_num() {
  num_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KGD_Num::num() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.KGD_Num.num)
  return num_.GetNoArena();
}
inline void KGD_Num::set_num(const ::std::string& value) {
  
  num_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.KGD_Num.num)
}
#if LANG_CXX11
inline void KGD_Num::set_num(::std::string&& value) {
  
  num_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.KGD_Num.num)
}
#endif
inline void KGD_Num::set_num(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  num_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.KGD_Num.num)
}
inline void KGD_Num::set_num(const char* value, size_t size) {
  
  num_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.KGD_Num.num)
}
inline ::std::string* KGD_Num::mutable_num() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.KGD_Num.num)
  return num_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KGD_Num::release_num() {
  // @@protoc_insertion_point(field_release:safeheron.proto.KGD_Num.num)
  
  return num_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KGD_Num::set_allocated_num(::std::string* num) {
  if (num != nullptr) {
    
  } else {
    
  }
  num_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), num);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.KGD_Num.num)
}

// string blindFactor = 2;
inline void KGD_Num::clear_blindfactor() {
  blindfactor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KGD_Num::blindfactor() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.KGD_Num.blindFactor)
  return blindfactor_.GetNoArena();
}
inline void KGD_Num::set_blindfactor(const ::std::string& value) {
  
  blindfactor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.KGD_Num.blindFactor)
}
#if LANG_CXX11
inline void KGD_Num::set_blindfactor(::std::string&& value) {
  
  blindfactor_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.KGD_Num.blindFactor)
}
#endif
inline void KGD_Num::set_blindfactor(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  blindfactor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.KGD_Num.blindFactor)
}
inline void KGD_Num::set_blindfactor(const char* value, size_t size) {
  
  blindfactor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.KGD_Num.blindFactor)
}
inline ::std::string* KGD_Num::mutable_blindfactor() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.KGD_Num.blindFactor)
  return blindfactor_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KGD_Num::release_blindfactor() {
  // @@protoc_insertion_point(field_release:safeheron.proto.KGD_Num.blindFactor)
  
  return blindfactor_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KGD_Num::set_allocated_blindfactor(::std::string* blindfactor) {
  if (blindfactor != nullptr) {
    
  } else {
    
  }
  blindfactor_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), blindfactor);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.KGD_Num.blindFactor)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_commitment_2eproto
