// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commitment.proto

#include "commitment.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_curve_5fpoint_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CurvePoint_curve_5fpoint_2eproto;
namespace safeheron {
namespace proto {
class KGDDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<KGD> _instance;
} _KGD_default_instance_;
class KGD_NumDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<KGD_Num> _instance;
} _KGD_Num_default_instance_;
}  // namespace proto
}  // namespace safeheron
static void InitDefaultsKGD_commitment_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::_KGD_default_instance_;
    new (ptr) ::safeheron::proto::KGD();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::safeheron::proto::KGD::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_KGD_commitment_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsKGD_commitment_2eproto}, {
      &scc_info_CurvePoint_curve_5fpoint_2eproto.base,}};

static void InitDefaultsKGD_Num_commitment_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::_KGD_Num_default_instance_;
    new (ptr) ::safeheron::proto::KGD_Num();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::safeheron::proto::KGD_Num::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_KGD_Num_commitment_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsKGD_Num_commitment_2eproto}, {}};

void InitDefaults_commitment_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_KGD_commitment_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_KGD_Num_commitment_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_commitment_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_commitment_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_commitment_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_commitment_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::KGD, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::KGD, y_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::KGD, blindfactor_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::KGD_Num, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::KGD_Num, num_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::KGD_Num, blindfactor_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::safeheron::proto::KGD)},
  { 7, -1, sizeof(::safeheron::proto::KGD_Num)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::safeheron::proto::_KGD_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::safeheron::proto::_KGD_Num_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_commitment_2eproto = {
  {}, AddDescriptors_commitment_2eproto, "commitment.proto", schemas,
  file_default_instances, TableStruct_commitment_2eproto::offsets,
  file_level_metadata_commitment_2eproto, 2, file_level_enum_descriptors_commitment_2eproto, file_level_service_descriptors_commitment_2eproto,
};

const char descriptor_table_protodef_commitment_2eproto[] =
  "\n\020commitment.proto\022\017safeheron.proto\032\021cur"
  "ve_point.proto\"B\n\003KGD\022&\n\001y\030\001 \001(\0132\033.safeh"
  "eron.proto.CurvePoint\022\023\n\013blindFactor\030\002 \001"
  "(\t\"+\n\007KGD_Num\022\013\n\003num\030\001 \001(\t\022\023\n\013blindFacto"
  "r\030\002 \001(\tb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_commitment_2eproto = {
  false, InitDefaults_commitment_2eproto, 
  descriptor_table_protodef_commitment_2eproto,
  "commitment.proto", &assign_descriptors_table_commitment_2eproto, 175,
};

void AddDescriptors_commitment_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_curve_5fpoint_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_commitment_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_commitment_2eproto = []() { AddDescriptors_commitment_2eproto(); return true; }();
namespace safeheron {
namespace proto {

// ===================================================================

void KGD::InitAsDefaultInstance() {
  ::safeheron::proto::_KGD_default_instance_._instance.get_mutable()->y_ = const_cast< ::safeheron::proto::CurvePoint*>(
      ::safeheron::proto::CurvePoint::internal_default_instance());
}
class KGD::HasBitSetters {
 public:
  static const ::safeheron::proto::CurvePoint& y(const KGD* msg);
};

const ::safeheron::proto::CurvePoint&
KGD::HasBitSetters::y(const KGD* msg) {
  return *msg->y_;
}
void KGD::clear_y() {
  if (GetArenaNoVirtual() == nullptr && y_ != nullptr) {
    delete y_;
  }
  y_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KGD::kYFieldNumber;
const int KGD::kBlindFactorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KGD::KGD()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:safeheron.proto.KGD)
}
KGD::KGD(const KGD& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  blindfactor_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.blindfactor().size() > 0) {
    blindfactor_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blindfactor_);
  }
  if (from.has_y()) {
    y_ = new ::safeheron::proto::CurvePoint(*from.y_);
  } else {
    y_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.KGD)
}

void KGD::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_KGD_commitment_2eproto.base);
  blindfactor_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  y_ = nullptr;
}

KGD::~KGD() {
  // @@protoc_insertion_point(destructor:safeheron.proto.KGD)
  SharedDtor();
}

void KGD::SharedDtor() {
  blindfactor_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete y_;
}

void KGD::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const KGD& KGD::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_KGD_commitment_2eproto.base);
  return *internal_default_instance();
}


void KGD::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.KGD)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  blindfactor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && y_ != nullptr) {
    delete y_;
  }
  y_ = nullptr;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* KGD::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<KGD*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .safeheron.proto.CurvePoint y = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::safeheron::proto::CurvePoint::_InternalParse;
        object = msg->mutable_y();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // string blindFactor = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.KGD.blindFactor");
        object = msg->mutable_blindfactor();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool KGD::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:safeheron.proto.KGD)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .safeheron.proto.CurvePoint y = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_y()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string blindFactor = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_blindfactor()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->blindfactor().data(), static_cast<int>(this->blindfactor().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.KGD.blindFactor"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:safeheron.proto.KGD)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:safeheron.proto.KGD)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void KGD::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:safeheron.proto.KGD)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .safeheron.proto.CurvePoint y = 1;
  if (this->has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::y(this), output);
  }

  // string blindFactor = 2;
  if (this->blindfactor().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blindfactor().data(), static_cast<int>(this->blindfactor().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.KGD.blindFactor");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->blindfactor(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:safeheron.proto.KGD)
}

::google::protobuf::uint8* KGD::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.KGD)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .safeheron.proto.CurvePoint y = 1;
  if (this->has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::y(this), target);
  }

  // string blindFactor = 2;
  if (this->blindfactor().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blindfactor().data(), static_cast<int>(this->blindfactor().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.KGD.blindFactor");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->blindfactor(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.KGD)
  return target;
}

size_t KGD::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.KGD)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string blindFactor = 2;
  if (this->blindfactor().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->blindfactor());
  }

  // .safeheron.proto.CurvePoint y = 1;
  if (this->has_y()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *y_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KGD::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.KGD)
  GOOGLE_DCHECK_NE(&from, this);
  const KGD* source =
      ::google::protobuf::DynamicCastToGenerated<KGD>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.KGD)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.KGD)
    MergeFrom(*source);
  }
}

void KGD::MergeFrom(const KGD& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.KGD)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.blindfactor().size() > 0) {

    blindfactor_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blindfactor_);
  }
  if (from.has_y()) {
    mutable_y()->::safeheron::proto::CurvePoint::MergeFrom(from.y());
  }
}

void KGD::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.KGD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KGD::CopyFrom(const KGD& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.KGD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KGD::IsInitialized() const {
  return true;
}

void KGD::Swap(KGD* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KGD::InternalSwap(KGD* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  blindfactor_.Swap(&other->blindfactor_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(y_, other->y_);
}

::google::protobuf::Metadata KGD::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_commitment_2eproto);
  return ::file_level_metadata_commitment_2eproto[kIndexInFileMessages];
}


// ===================================================================

void KGD_Num::InitAsDefaultInstance() {
}
class KGD_Num::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KGD_Num::kNumFieldNumber;
const int KGD_Num::kBlindFactorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KGD_Num::KGD_Num()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:safeheron.proto.KGD_Num)
}
KGD_Num::KGD_Num(const KGD_Num& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  num_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.num().size() > 0) {
    num_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.num_);
  }
  blindfactor_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.blindfactor().size() > 0) {
    blindfactor_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blindfactor_);
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.KGD_Num)
}

void KGD_Num::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_KGD_Num_commitment_2eproto.base);
  num_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  blindfactor_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

KGD_Num::~KGD_Num() {
  // @@protoc_insertion_point(destructor:safeheron.proto.KGD_Num)
  SharedDtor();
}

void KGD_Num::SharedDtor() {
  num_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  blindfactor_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void KGD_Num::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const KGD_Num& KGD_Num::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_KGD_Num_commitment_2eproto.base);
  return *internal_default_instance();
}


void KGD_Num::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.KGD_Num)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  num_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  blindfactor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* KGD_Num::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<KGD_Num*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string num = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.KGD_Num.num");
        object = msg->mutable_num();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string blindFactor = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.KGD_Num.blindFactor");
        object = msg->mutable_blindfactor();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool KGD_Num::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:safeheron.proto.KGD_Num)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string num = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_num()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->num().data(), static_cast<int>(this->num().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.KGD_Num.num"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string blindFactor = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_blindfactor()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->blindfactor().data(), static_cast<int>(this->blindfactor().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.KGD_Num.blindFactor"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:safeheron.proto.KGD_Num)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:safeheron.proto.KGD_Num)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void KGD_Num::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:safeheron.proto.KGD_Num)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string num = 1;
  if (this->num().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->num().data(), static_cast<int>(this->num().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.KGD_Num.num");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->num(), output);
  }

  // string blindFactor = 2;
  if (this->blindfactor().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blindfactor().data(), static_cast<int>(this->blindfactor().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.KGD_Num.blindFactor");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->blindfactor(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:safeheron.proto.KGD_Num)
}

::google::protobuf::uint8* KGD_Num::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.KGD_Num)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string num = 1;
  if (this->num().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->num().data(), static_cast<int>(this->num().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.KGD_Num.num");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->num(), target);
  }

  // string blindFactor = 2;
  if (this->blindfactor().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->blindfactor().data(), static_cast<int>(this->blindfactor().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.KGD_Num.blindFactor");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->blindfactor(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.KGD_Num)
  return target;
}

size_t KGD_Num::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.KGD_Num)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string num = 1;
  if (this->num().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->num());
  }

  // string blindFactor = 2;
  if (this->blindfactor().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->blindfactor());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KGD_Num::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.KGD_Num)
  GOOGLE_DCHECK_NE(&from, this);
  const KGD_Num* source =
      ::google::protobuf::DynamicCastToGenerated<KGD_Num>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.KGD_Num)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.KGD_Num)
    MergeFrom(*source);
  }
}

void KGD_Num::MergeFrom(const KGD_Num& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.KGD_Num)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.num().size() > 0) {

    num_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.num_);
  }
  if (from.blindfactor().size() > 0) {

    blindfactor_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.blindfactor_);
  }
}

void KGD_Num::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.KGD_Num)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KGD_Num::CopyFrom(const KGD_Num& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.KGD_Num)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KGD_Num::IsInitialized() const {
  return true;
}

void KGD_Num::Swap(KGD_Num* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KGD_Num::InternalSwap(KGD_Num* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  num_.Swap(&other->num_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  blindfactor_.Swap(&other->blindfactor_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata KGD_Num::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_commitment_2eproto);
  return ::file_level_metadata_commitment_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace safeheron
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::safeheron::proto::KGD* Arena::CreateMaybeMessage< ::safeheron::proto::KGD >(Arena* arena) {
  return Arena::CreateInternal< ::safeheron::proto::KGD >(arena);
}
template<> PROTOBUF_NOINLINE ::safeheron::proto::KGD_Num* Arena::CreateMaybeMessage< ::safeheron::proto::KGD_Num >(Arena* arena) {
  return Arena::CreateInternal< ::safeheron::proto::KGD_Num >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
